repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.4.6
  hooks:
    # Run the linter.
    - id: ruff
      types_or: [ python, pyi, jupyter ]
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi, jupyter ]
- repo: https://github.com/meliache/pre-commit-chktex
  rev: v0.2.2
  hooks:
    - id: chktex-system
      exclude: "/templates/.*"
